version: "3.9"

services:
  server:
    build: ./server
    container_name: task-manager-server
    ports:
      - "5001:5000"
    networks:
      - app-network

  client:
    build: ./client
    container_name: task-manager-client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
